{% set name = "jproperties" %}
{% set version = "2.1.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jproperties-{{ version }}.tar.gz
  sha256: 40b71124e8d257e8954899a91cd2d5c0f72e0f67f1b72048a5ba264567604f29

build:
  number: 0
  noarch: python
  entry_points:
    - propconv = jproperties:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest-runner ~=2.0
    - python >=3.6
  run:
    - python >=3.6
    - six ~=1.12

test:
  imports:
    - jproperties
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Tblue/python-jproperties
  summary: Java Property file parser and writer for Python
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - melonhead901
